apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todoapp
  name: deployment-todoapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-todoapp
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-todoapp
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest # public.ecr.aws/l6m2t8p7/docker-2048:latest # yashgangwar123/todo-app-efk:latest
        imagePullPolicy: Always
        name: todoapp
        ports:
        - containerPort: 80
        
