apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efklog
data:
  fluent.conf: |
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag kubernetes.*
      <parse>
        @type none
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type parser
      key_name log
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format regexp
          expression /^(?<time>[^ ]+ [^ ]+) (?<stream>[^ ]+) (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>

    <match kubernetes.**>
      @type elasticsearch
      @log_level debug
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      logstash_format true
      logstash_prefix fluentd
      logstash_dateformat %Y.%m.%d
      type_name _doc
      <buffer>
        flush_interval 10s
      </buffer>
    </match>
