apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: efklog
data:
  fluent.conf: |
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag kubernetes.*
      <parse>
        @type none
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type parser
      key_name message
      reserve_data true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format regexp
          expression /^(?<time>[^ ]+T[^ ]+\.[^ ]+Z) (?<stream>stdout|stderr) (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
      </parse>
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      <record>
        log ${record["log"].strip if record["log"]}
      </record>
    </filter>

    <match kubernetes.**>
      @type elasticsearch
      @log_level debug
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'es-cluster.efklog.svc.cluster.local'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      logstash_format true
      logstash_prefix fluentd
      logstash_dateformat %Y.%m.%d
      type_name _doc
      <buffer>
        flush_interval 10s
      </buffer>
    </match>
