apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: efklog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.13.4
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://es-cluster:9200
        - name: SERVER_BASEPATH
          value: "/kibana"
        - name: SERVER_REWRITEBASEPATH
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: efklog
spec:
  ports:
  - port: 5601
    protocol: TCP
  selector:
    app: kibana
