apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.13.4
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: http://es-cluster:9200
